module.exports = {
  CONNECT: 'CONNECT',
  CREATE_USER: 'CREATE_USER',
  DISCONNECT: 'DISCONNECT',
  LIST_USER: 'LIST_USER',
  DELETE_USER: 'DELETE_USER',
  EDIT_USER: 'EDIT_USER',
  ON_HOME: 'ON_HOME',
};
